# Generated by Django 2.2.5 on 2019-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationId', models.CharField(default='0-0', max_length=10, unique=True, verbose_name='Location Id')),
                ('description', models.TextField(blank=True, verbose_name='Location Description')),
                ('locationType', models.CharField(choices=[('Forest', 'Forest'), ('Desert', 'Desert'), ('Dungeon', 'Dungeon'), ('River', 'River'), ('Ocean', 'Ocean')], default='Forest', max_length=15, verbose_name='Location Type')),
            ],
        ),
    ]
