# Generated by Django 2.2.5 on 2019-09-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageText', models.TextField(blank=True, max_length=1000, verbose_name='MessageText')),
                ('playerFrom', models.ForeignKey(on_delete='', related_name='PlayerFrom', to='Player.Player')),
                ('playerTo', models.ForeignKey(on_delete='', related_name='PlayerTo', to='Player.Player')),
            ],
        ),
    ]
