# Generated by Django 2.2.5 on 2019-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.ForeignKey(on_delete='', to='Inventory.ItemType'),
        ),
    ]
