# Generated by Django 2.2.5 on 2019-09-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_auto_20190910_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemtype',
            old_name='type',
            new_name='name',
        ),
    ]
